export const foodCategories = {
  seedOils: [
    "vegetable oil",
    "canola oil",
    "sunflower oil",
    "palm oil",
    "palm kernel oil",
    "soybean oil",
    "cottonseed oil",
    "safflower oil",
    "sesame oil",
    "grapeseed oil",
    "flaxseed oil",
    "hemp seed oil",
    "mustard seed oil",
    "chia seed oil",
    "pumpkin seed oil",
    "poppy seed oil",
    "sunflower lecithin",
    "safflower oleosomes",
    "grapeseed extract",
    "flaxseed meal",
    "hemp seed protein",
    "pumpkin seed protein",
    "poppy seed paste",
    "mustard seed powder",
    "cottonseed meal",
    "chia seed gel",
  ],
  bugs: [
    "crickets",
    "cricket flour",
    "mealworms",
    "mealworm flour",
    "black soldier fly larvae",
    "insect protein isolate",
    "silkworm pupae",
    "grasshoppers",
    "locusts",
    "ant larvae",
    "cricket oil",
    "chitin",
  ],
  commonAllergens: [
    "peanuts",
    "almonds",
    "cashews",
    "walnuts",
    "hazelnuts",
    "milk",
    "eggs",
    "salmon",
    "tuna",
    "cod",
    "crab",
    "lobster",
    "shrimp",
    "prawns",
    "wheat",
    "soy",
    "sesame seeds",
    "mustard",
    "celery",
    "sulfites",
    "lupin",
    "snails",
    "squid",
    "octopus",
    "corn",
    "gluten",
    "coconut",
    "kiwi",
    "banana",
    "avocado",
    "chocolate",
    "garlic",
    "onion",
    "peach",
    "strawberry",
    "tomato",
    "cherry",
    "pineapple",
    "melon",
    "citrus fruits",
    "apple",
    "grape",
    "watermelon",
  ],
  artificialAdditivesInFood: [
    "red 40",
    "yellow 5",
    "yellow 6",
    "blue 1",
    "blue 2",
    "green 3",
    "red 3",
    "caramel color",
    "titanium dioxide",
    "carmine",
    "ethyl vanillin",
    "methyl salicylate",
    "isoamyl acetate",
    "ethyl maltol",
    "benzaldehyde",
    "limonene",
    "ethyl butyrate",
    "diacetyl",
    "methyl anthranilate",
    "linalool",
    "ethyl acetate",
    "allyl hexanoate",
    "cinnamaldehyde",
    "menthol",
    "vanillin",
    "acetoin",
    "furaneol",
    "isobutyl acetate",
    "gamma-undecalactone",
    "methyl cinnamate",
  ],
  bannedInEU: [
    "bha",
    "butylated hydroxyanisole",
    "bht",
    "butylated hydroxytoluene",
    "cyclamate",
    "e952",
    "aspartame",
    "e951",
    "tartrazine",
    "e102",
    "quinoline yellow",
    "e104",
    "sunset yellow fcf",
    "e110",
    "allura red ac",
    "e129",
    "ponceau 4r",
    "e124",
    "azorubine/carmoisine",
    "e122",
    "brominated vegetable oil",
    "potassium nitrate",
    "sodium nitrite",
    "quinines",
    "monosodium glutamate",
  ],
  nonVegetarian: [
    "beef",
    "pork",
    "chicken",
    "turkey",
    "duck",
    "lamb",
    "venison",
    "fish",
    "shellfish",
    "shrimp",
    "crab",
    "lobster",
    "mussels",
    "squid",
    "octopus",
    "clams",
    "anchovies",
    "bacon",
    "salmon",
    "tuna",
    "sausage",
    "pepperoni",
    "ham",
    "salami",
    "pate",
    "liver",
    "kidney",
    "tripe",
    "tongue",
    "gelatin",
    "rennet",
    "worcestershire sauce",
    "fish sauce",
    "oyster sauce",
    "anchovy paste",
    "isinglass",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "pepsin",
    "cochineal",
    "shellac",
    "l-cysteine",
  ],
  nonVegan: [
    "gelatin",
    "honey",
    "beeswax",
    "carmine (e120)",
    "casein",
    "lactose",
    "whey",
    "isinglass",
    "shellac (e904)",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "cochineal",
    "pepsin",
    "collagen",
    "elastin",
    "keratin",
    "rennet",
    "tallow",
    "diglyceride",
    "stearic acid",
    "magnesium stearate",
    "omega3 fatty acids",
    "cysteine",
    "guanine",
    "squalene",
  ],
  dairy: [
    "milk",
    "butter",
    "cheese",
    "yogurt",
    "cream",
    "sour cream",
    "cream cheese",
    "cottage cheese",
    "mascarpone",
    "ricotta",
    "condensed milk",
    "evaporated milk",
    "powdered milk",
    "ice cream",
    "gelato",
    "sherbet",
    "frozen yogurt",
    "whipped cream",
    "milk powder",
    "cheese powder",
    "whey",
    "casein",
    "lactose",
    "buttermilk",
    "kefir",
    "clotted cream",
    "skim milk",
    "low fat milk",
    "full fat milk",
    "chocolate milk",
  ],
  addedSugar: [
    "sugar",
    "high fructose corn syrup",
    "honey",
    "maple syrup",
    "corn syrup",
    "brown sugar",
    "powdered sugar",
    "cane sugar",
    "molasses",
    "fructose",
    "glucose",
    "syrup",
    "dextrose",
    "sucrose",
    "corn sweetener",
  ],
  nuts: [
    "almonds",
    "almond butter",
    "almond extract",
    "cashews",
    "hazelnuts",
    "macadamia nuts",
    "peanuts",
    "pecans",
    "pine nuts",
    "pistachios",
    "walnuts",
  ],
  forbiddenPork: [
    "pork",
    "gelatin",
    "lard",
    "bacon",
    "ham",
    "sausage",
    "prosciutto",
    "pancetta",
  ],
  haram: [
    "alcohol",
    "ethyl alcohol",
    "crickets",
    "mealworms",
    "pork",
    "bacon",
    "ham",
  ],
};

export default foodCategories;
