// Define a mapping of alternate names to their canonical names
export const alternateNames = {
  msg: "monosodium glutamate",
  "sodium glutamate": "monosodium glutamate",
  "flavor enhancer": "monosodium glutamate",
  e621: "monosodium glutamate",

  // Add more alternate mappings as needed
  "veg oil": "vegetable oil",
  "veggie oil": "vegetable oil",

  hfcs: "high fructose corn syrup",
  "corn syrup solids": "corn syrup",

  "fd&c red 40": "red 40",
  "fd&c yellow 5": "yellow 5",
  "fd&c yellow 6": "yellow 6",
  "fd&c blue 1": "blue 1",

  peanut: "peanuts",
  almond: "almonds",
  walnut: "walnuts",

  // Add as many alternates as you need
}

export const foodCategories = {
  "Seed oils": [
    "vegetable oil",
    "canola oil",
    "sunflower oil",
    "palm oil",
    "palm kernel oil",
    "soybean oil",
    "cottonseed oil",
    "safflower oil",
    "sesame oil",
    "grapeseed oil",
    "flaxseed oil",
    "hemp seed oil",
    "mustard seed oil",
    "chia seed oil",
    "pumpkin seed oil",
    "poppy seed oil",
    "sunflower lecithin",
    "safflower oleosomes",
    "grapeseed extract",
    "flaxseed meal",
    "hemp seed protein",
    "pumpkin seed protein",
    "poppy seed paste",
    "mustard seed powder",
    "cottonseed meal",
    "chia seed gel",
  ],
  "Insect Parts": [
    "crickets",
    "cricket flour",
    "mealworms",
    "mealworm flour",
    "black soldier fly larvae",
    "insect protein isolate",
    "silkworm pupae",
    "grasshoppers",
    "locusts",
    "ant larvae",
    "cricket oil",
    "chitin",
  ],
  "Common allergens": [
    "peanuts",
    "almonds",
    "cashews",
    "walnuts",
    "hazelnuts",
    "milk",
    "eggs",
    "salmon",
    "tuna",
    "cod",
    "crab",
    "lobster",
    "shrimp",
    "prawns",
    "wheat",
    "soy",
    "sesame seeds",
    "mustard",
    "celery",
    "sulfites",
    "lupin",
    "snails",
    "squid",
    "octopus",
    "corn",
    "gluten",
    "coconut",
    "kiwi",
    "banana",
    "avocado",
    "chocolate",
    "garlic",
    "onion",
    "peach",
    "strawberry",
    "tomato",
    "cherry",
    "pineapple",
    "melon",
    "citrus fruits",
    "apple",
    "grape",
    "watermelon",
    "natural flavors"
  ],
  "Artificial additives": [
    "red 40",
    "yellow 5",
    "yellow 6",
    "blue 1",
    "blue 2",
    "green 3",
    "red 3",
    "caramel color",
    "titanium dioxide",
    "carmine",
    "ethyl vanillin",
    "methyl salicylate",
    "isoamyl acetate",
    "ethyl maltol",
    "benzaldehyde",
    "limonene",
    "ethyl butyrate",
    "diacetyl",
    "methyl anthranilate",
    "linalool",
    "ethyl acetate",
    "allyl hexanoate",
    "cinnamaldehyde",
    "menthol",
    "vanillin",
    "acetoin",
    "furaneol",
    "isobutyl acetate",
    "gamma-undecalactone",
    "methyl cinnamate",
  ],
  "Banned in Europe": [
    "bha",
    "butylated hydroxyanisole",
    "bht",
    "butylated hydroxytoluene",
    "cyclamate",
    "e952",
    "aspartame",
    "e951",
    "tartrazine",
    "e102",
    "quinoline yellow",
    "e104",
    "sunset yellow fcf",
    "e110",
    "allura red ac",
    "e129",
    "ponceau 4r",
    "e124",
    "azorubine/carmoisine",
    "e122",
    "brominated vegetable oil",
    "potassium nitrate",
    "sodium nitrite",
    "quinines",
    "monosodium glutamate",
  ],
  "Meat products": [
    "beef",
    "pork",
    "chicken",
    "turkey",
    "duck",
    "lamb",
    "venison",
    "fish",
    "shellfish",
    "shrimp",
    "crab",
    "lobster",
    "mussels",
    "squid",
    "octopus",
    "clams",
    "anchovies",
    "bacon",
    "salmon",
    "tuna",
    "sausage",
    "pepperoni",
    "ham",
    "salami",
    "pate",
    "liver",
    "kidney",
    "tripe",
    "tongue",
    "gelatin",
    "rennet",
    "worcestershire sauce",
    "fish sauce",
    "oyster sauce",
    "anchovy paste",
    "isinglass",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "pepsin",
    "cochineal",
    "shellac",
    "l-cysteine",
  ],
  "Non Vegan": [
    "gelatin",
    "honey",
    "beeswax",
    "carmine (e120)",
    "casein",
    "lactose",
    "whey",
    "isinglass",
    "shellac (e904)",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "cochineal",
    "pepsin",
    "collagen",
    "elastin",
    "keratin",
    "rennet",
    "tallow",
    "diglyceride",
    "stearic acid",
    "magnesium stearate",
    "omega3 fatty acids",
    "cysteine",
    "guanine",
    "squalene"
    
  ],
  Dairy: [
    "milk",
    "butter",
    "cheese",
    "yogurt",
    "cream",
    "sour cream",
    "cream cheese",
    "cottage cheese",
    "mascarpone",
    "ricotta",
    "condensed milk",
    "evaporated milk",
    "powdered milk",
    "ice cream",
    "gelato",
    "sherbet",
    "frozen yogurt",
    "whipped cream",
    "milk powder",
    "cheese powder",
    "whey",
    "casein",
    "lactose",
    "buttermilk",
    "kefir",
    "clotted cream",
    "skim milk",
    "low fat milk",
    "full fat milk",
    "chocolate milk",
  ],
  "Added Sugar": [
    "sugar",
    "high fructose corn syrup",
    "honey",
    "maple syrup",
    "corn syrup",
    "brown sugar",
    "powdered sugar",
    "cane sugar",
    "molasses",
    "fructose",
    "glucose",
    "syrup",
    "dextrose",
    "sucrose",
    "corn sweetener",
  ],
  Nuts: [
    "almonds",
    "almond butter",
    "almond extract",
    "cashews",
    "hazelnuts",
    "macadamia nuts",
    "peanuts",
    "pecans",
    "pine nuts",
    "pistachios",
    "walnuts",
  ],
  "Pork products": ["pork", "gelatin", "lard", "bacon", "ham", "sausage", "prosciutto", "pancetta"],
  "Islamic Law": [
    "alcohol",
    "ethyl alcohol",
    "crickets",
    "mealworms",
    "pork",
    "bacon",
    "ham",
    "gelatin",
    "sausage",
    "prosciutto",
    "pancetta",
  ],
  Kosher: [
    "pork",
    "bacon",
    "ham",
    "prosciutto",
    "pepperoni",
    "lobster",
    "crab",
    "shrimp",
    "clam",
    "scallop",
    "oyster",
    "catfish",
    "eel",
    "rabbit",
    "horse",
    "camel",
    "bat ",
    "alligator meat",
    "frog legs",
    "blood sausage",
    "black pudding",
    "cheeseburger",
    "gelatin",
    "rennet",
    "shellfish sauce",
    "imitation crab",
  ],
  "Nitrates": [
    "sodium nitrate",
    "sodium nitrite",
    "potassium nitrate",
    "potassium nitrite",
    "calcium nitrate",
    "calcium nitrite",
    "nitrate of soda",
    "nitrate of potash",
    "nitrate-cured salt",
    "celery powder",
    "celery juice powder",
    "beet powder",
    "spinach powder"
  ],
  "Added texturizers": [
    "monosodium glutamate (MSG)",
    "disodium inosinate",
    "disodium guanylate",
    "disodium 5'-ribonucleotides",
    "yeast extract",
    "autolyzed yeast",
    "hydrolyzed vegetable protein",
    "hydrolyzed soy protein",
    "torula yeast",
    "maltodextrin",
    "modified food starch",
    "xanthan gum",
    "guar gum",
    "locust bean gum",
    "carrageenan",
    "pectin",
    "agar agar",
    "lecithin",
    "gellan gum",
    "cellulose gum",
    "propylene glycol alginate",
    "microcrystalline cellulose",
    "polysorbate 80",
    "sorbitan monostearate",
    "monoglyceride",
    "diglyceride",
    "calcium stearoyl lactylate"
  ],
  "Preservatives": [
    "sodium benzoate",
    "potassium sorbate",
    "calcium propionate",
    "sodium propionate",
    "sodium nitrite",
    "sodium nitrate",
    "sulfur dioxide",
    "sodium bisulfite",
    "potassium bisulfite",
    "sodium metabisulfite",
    "potassium metabisulfite",
    "BHA",
    "butylated hydroxyanisole",
    "BHT",
    "butylated hydroxytoluene",
    "TBHQ",
    "tertiary butylhydroquinone",
    "EDTA",
    "ethylenediaminetetraacetic acid",
    "calcium disodium EDTA",
    "natamycin",
    "nisin",
    "propylene glycol",
    "sorbic acid",
    "benzoic acid",
    "lactic acid",
    "citric acid",
    "ascorbic acid",
    "tocopherols",
    "acetic acid"
  ]
  
}

// Helper function to normalize an ingredient name
export const normalizeIngredient = (ingredient) => {
  const normalized = ingredient.toLowerCase().trim()
  return alternateNames[normalized] || normalized
}

// Helper function to check if an ingredient is in a category
export const isIngredientInCategory = (ingredient, category) => {
  const normalizedIngredient = normalizeIngredient(ingredient)
  return foodCategories[category].some((item) => normalizeIngredient(item) === normalizedIngredient)
}

// Helper function to find which categories an ingredient belongs to
export const findIngredientCategories = (ingredient) => {
  const normalizedIngredient = normalizeIngredient(ingredient)
  return Object.keys(foodCategories).filter((category) =>
    foodCategories[category].some((item) => normalizeIngredient(item) === normalizedIngredient),
  )
}

export default foodCategories
