
  // Seed Oils
  const seedOils = [
    "vegetable oil",
    "canola oil",
    "sunflower oil",
    "palm oil",
    "palm kernel oil",
    "soybean oil",
    "cottonseed oil",
    "safflower oil",
    "sesame oil",
    "grapeseed oil",
    "flaxseed oil",
    "hemp seed oil",
    "mustard seed oil",
    "chia seed oil",
    "pumpkin seed oil",
    "poppy seed oil",
    "sunflower lecithin",
    "safflower oleosomes",
    "grapeseed extract",
    "flaxseed meal",
    "hemp seed protein",
    "pumpkin seed protein",
    "poppy seed paste",
    "mustard seed powder",
    "cottonseed meal",
    "chia seed gel"
  ];
  
  // Bugs
  const bugs = [
    "crickets",
    "cricket flour",
    "mealworms",
    "mealworm flour",
    "black soldier fly larvae",
    "insect protein isolate",
    "silkworm pupae",
    "grasshoppers",
    "locusts",
    "ant larvae",
    "cricket oil",
    "chitin"
  ];
  
  // Common Allergens
  const commonAllergens = [
    "peanuts",
    "almonds",
    "cashews",
    "walnuts",
    "hazelnuts",
    "milk",
    "eggs",
    "salmon",
    "tuna",
    "cod",
    "crab",
    "lobster",
    "shrimp",
    "prawns",
    "wheat",
    "soy",
    "sesame seeds",
    "mustard",
    "celery",
    "sulfites",
    "lupin",
    "snails",
    "squid",
    "octopus",
    "corn",
    "gluten",
    "coconut",
    "kiwi",
    "banana",
    "avocado",
    "chocolate",
    "garlic",
    "onion",
    "peach",
    "strawberry",
    "tomato",
    "cherry",
    "pineapple",
    "melon",
    "citrus fruits",
    "apple",
    "grape",
    "watermelon"
  ];
  
  // Artificial Additives in Food
  const artificialAdditivesInFood = [
    "red 40",
    "yellow 5",
    "yellow 6",
    "blue 1",
    "blue 2",
    "green 3",
    "red 3",
    "caramel color",
    "titanium dioxide",
    "carmine",
    "ethyl vanillin",
    "methyl salicylate",
    "isoamyl acetate",
    "ethyl maltol",
    "benzaldehyde",
    "limonene",
    "ethyl butyrate",
    "diacetyl",
    "methyl anthranilate",
    "linalool",
    "ethyl acetate",
    "allyl hexanoate",
    "cinnamaldehyde",
    "menthol",
    "vanillin",
    "acetoin",
    "furaneol",
    "isobutyl acetate",
    "gamma-undecalactone",
    "methyl cinnamate"
  ];
  
  // Banned in EU
  const bannedInEU = [
    "bha",
    "butylated hydroxyanisole",
    "bht",
    "butylated hydroxytoluene",
    "cyclamate",
    "e952",
    "aspartame",
    "e951",
    "tartrazine",
    "e102",
    "quinoline yellow",
    "e104",
    "sunset yellow fcf",
    "e110",
    "allura red ac",
    "e129",
    "ponceau 4r",
    "e124",
    "azorubine/carmoisine",
    "e122",
    "brominated vegetable oil",
    "potassium nitrate",
    "sodium nitrite",
    "quinines",
    "monosodium glutamate"
  ];
  
  // Non-Vegetarian
  const nonVegetarian = [
    "beef",
    "pork",
    "chicken",
    "turkey",
    "duck",
    "lamb",
    "venison",
    "fish",
    "shellfish",
    "shrimp",
    "crab",
    "lobster",
    "mussels",
    "squid",
    "octopus",
    "clams",
    "anchovies",
    "bacon",
    "salmon",
    "tuna",
    "sausage",
    "pepperoni",
    "ham",
    "salami",
    "pate",
    "liver",
    "kidney",
    "tripe",
    "tongue",
    "gelatin",
    "rennet",
    "worcestershire sauce",
    "fish sauce",
    "oyster sauce",
    "anchovy paste",
    "isinglass",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "pepsin",
    "cochineal",
    "shellac",
    "l-cysteine"
  ];
  
  // Only Vegan
  const onlyVegan = [
    "gelatin",
    "honey",
    "beeswax",
    "carmine (e120)",
    "casein",
    "lactose",
    "whey",
    "isinglass",
    "shellac (e904)",
    "lard",
    "schmaltz",
    "ghee",
    "clarified butter",
    "cochineal",
    "pepsin",
    "collagen",
    "elastin",
    "keratin",
    "rennet",
    "tallow",
    "diglyceride",
    "stearic acid",
    "magnesium stearate",
    "omega3 fatty acids",
    "cysteine",
    "guanine",
    "squalene"
  ];
  

  
  // Added Sugar
  const addedSugar = [
    "sugar",
    "high fructose corn syrup",
    "honey",
    "maple syrup",
    "corn syrup",
    "brown sugar",
    "powdered sugar",
    "cane sugar",
    "confectioner's sugar",
    "molasses",
    "fructose",
    "glucose",
    "syrup",
    "dextrose",
    "sucrose",
    "corn sweetener",
    "corn syrup solids",
    "crystalline fructose",
    "caramel",
    "agave nectar",
    "coconut sugar",
    "date sugar",
    "golden syrup",
    "treacle",
    "fruit juice concentrate",
    "invert sugar",
    "raw sugar",
    "refiner's syrup",
    "turbinado sugar",
    "evaporated cane juice",
    "icing sugar",
    "demerara sugar",
    "beet sugar",
    "blackstrap molasses",
    "brown rice syrup",
    "barley malt",
    "cane juice",
    "cane crystals",
    "carob syrup",
    "castor sugar",
    "galactose",
    "grape sugar",
    "isomalt",
    "lactose",
    "malt extract",
    "malt syrup",
    "maltitol",
    "maltodextrin",
    "maltose",
    "monosaccharides",
    "nectar",
    "palm sugar",
    "panocha",
    "rice syrup",
    "saccharose",
    "sorghum syrup",
    "yellow sugar",
    "yacon syrup"
  ];
  
  // Dairy
  const dairy = [
    "milk",
    "butter",
    "cheese",
    "yogurt",
    "cream",
    "sour cream",
    "cream cheese",
    "cottage cheese",
    "mascarpone",
    "ricotta",
    "condensed milk",
    "evaporated milk",
    "powdered milk",
    "ice cream",
    "gelato",
    "sherbet",
    "frozen yogurt",
    "whipped cream",
    "milk powder",
    "cheese powder",
    "whey",
    "casein",
    "lactose",
    "buttermilk",
    "kefir",
    "clotted cream",
    "goat milk",
    "sheep milk",
    "buffalo milk",
    "camel milk",
    "horse milk",
    "donkey milk",
    "moose milk",
    "reindeer milk",
    "yak milk",
    "bison milk",
    "elk milk",
    "zebu milk",
    "ewe milk",
    "water buffalo milk",
    "a2 milk",
    "skim milk",
    "low fat milk",
    "full fat milk",
    "flavored milk",
    "chocolate milk",
    "strawberry milk",
    "banana milk",
    "soy yogurt",
    "milkfat",
    "milk solids",
    "milk protein concentrate",
    "milk protein isolate",
    "milk permeate",
    "buttermilk powder",
    "lactose powder",
    "whey powder",
    "whey protein concentrate",
    "whey protein isolate",
    "casein powder",
    "caseinate",
    "lactalbumin",
    "lactoferrin",
    "lactulose",
    "lactic acid",
    "galactose",
    "ghee"
  ];
  
  // Forbidden Pork
  const forbiddenPork = [
    "pork",
    "gelatin",
    "lard",
    "lard oil",
    "pork flavoring",
    "bacon",
    "ham",
    "sausage",
    "pork pastrami",
    "prosciutto",
    "pancetta",
    "coppa",
    "capicola",
    "guanciale",
    "fatback"
  ];
  
  // Nuts
  const nuts = [
    "almonds",
    "almond butter",
    "almond extract",
    "almond meal/flour",
    "almond milk",
    "brazil nuts",
    "cashews",
    "cashew butter",
    "cashew milk",
    "chestnuts",
    "hazelnuts",
    "filberts",
    "hazelnut butter",
    "hazelnut oil",
    "macadamia nuts",
    "macadamia nut oil",
    "peanuts",
    "peanut butter",
    "peanut oil",
    "pecans",
    "pine nuts",
    "pignoli",
    "pistachios",
    "walnuts"
  ];
  
  // Haram
  const haram = [...forbiddenPork, "alcohol", "ethyl alcohol", ...bugs];
  
  // Heavy Metals (empty as no items were provided)

 // Non-Vegan
 const nonVegan = [
    ...onlyVegan,
    ...nonVegetarian,
    ...dairy
  ];


  const keywordLists = [
    { "seed-oils": seedOils },
    { "bugs": bugs },
    { "banned-in-eu": bannedInEU },
    { "non-vegetarian": nonVegetarian },
    { "non-vegan": nonVegan },
    { "haram": haram },
    { "added-sugar": addedSugar },
    { "dairy": dairy },
    { "nuts": nuts },
    { "common-allergens": commonAllergens },
    { "artificial-additives-in-food": artificialAdditivesInFood },
    { "only-vegan": onlyVegan },
    { "forbidden-pork": forbiddenPork }
  ];
  
  export default keywordLists;
  