List<Map<String, List<String>>> keywordLists = [
  // LIST THEM ALL HERE, lowercase and with kebab case
  {"seed-oils": seedOils},
  {"bugs": bugs},
  {"banned-in-eu": bannedInEU},
  {"non-vegetarian": nonVegetarian},
  {"non-vegan": nonVegan},
  {"haram": haram},
  {"heavy-metals": heavyMetals},
  {"added-sugar": addedSugar},
  {"dairy": dairy},
];

List<String> seedOils = [
  "sunflower oil",
  "sunflower lecithin",
  "sesame oil",
  "sesamin",
  "safflower oil",
  "safflower oleosomes",
  "grapeseed oil",
  "grapeseed extract",
  "flaxseed oil",
  "flaxseed meal",
  "chia seed oil",
  "chia seed gel",
  "pumpkin seed oil",
  "pumpkin seed protein",
  "hemp seed oil",
  "hemp seed protein",
  "poppy seed oil",
  "poppy seed paste",
  "mustard seed oil",
  "mustard seed powder",
  "cottonseed oil",
  "cottonseed meal",
  "vegetable oil",
  "canola oil",
  "palm oil"
];
List<String> bugs = [
  "Crickets",
  "Cricket flour",
  "Mealworms",
  "Mealworm flour",
  "Black soldier fly larvae",
  "Insect protein isolate",
  "Silkworm pupae",
  "Grasshoppers",
  "Locusts",
  "Ant larvae",
  "Cricket oil",
  "Chitin",
];
List<String> bannedInEU = [
  "BHA (Butylated Hydroxyanisole)",
  "BHT (Butylated Hydroxytoluene)",
  "Cyclamate (E952)",
  "Aspartame (E951)",
  "Tartrazine (E102)",
  "Quinoline Yellow (E104)",
  "Sunset Yellow FCF (E110)",
  "Allura Red AC (E129)",
  "Ponceau 4R (E124)",
  "Azorubine/Carmoisine (E122)",
  "Brominated Vegetable Oil (BVO)",
  "Tartrazine (E102)",
  "Quinoline Yellow (E104)",
  "Sunset Yellow FCF (E110)",
  "Allura Red AC (E129)",
  "Ponceau 4R (E124)",
  "Azorubine/Carmoisine (E122)",
  "Cyclamate (E952)",
  "Aspartame (E951)",
  "Potassium Nitrate",
  "Sodium Nitrite",
  "Quinines",
  "Monosodium Glutamate (MSG)",
];
List<String> nonVegetarian = [
  "Beef",
  "Pork",
  "Chicken",
  "Turkey",
  "Duck",
  "Lamb",
  "Venison",
  "Fish",
  "Shellfish",
  "Shrimp",
  "Crab",
  "Lobster",
  "Mussels",
  "Squid",
  "Octopus",
  "Clams",
  "Anchovies",
  "Bacon",
  "Salmon",
  "Tuna",
  "Sausage",
  "Pepperoni",
  "Ham",
  "Salami",
  "Pate",
  "Liver",
  "Kidney",
  "Tripe",
  "Tongue",
  "Gelatin",
  "Broth (meat-based)",
  "Gelatin",
  "Broth (meat-based)",
  "Rennet",
  "Worcestershire sauce",
  "Fish sauce",
  "Oyster sauce",
  "Anchovy paste",
  "Isinglass",
  "Lard",
  "Schmaltz",
  "Ghee (clarified butter)",
  "Pepsin",
  "Cochineal (E120)",
  "Shellac (E904)",
  "L-cysteine",
];
List<String> nonVegan = [
  "Gelatin",
  "Honey",
  "Beeswax",
  "Carmine (E120)",
  "Casein",
  "Lactose",
  "Whey",
  "Isinglass",
  "Shellac (E904)",
  "Lard",
  "Schmaltz",
  "Ghee",
  "clarified butter"
      "Cochineal (E120)",
  "Pepsin",
  "Collagen",
  "Elastin",
  "Keratin",
  "Rennet",
  "Tallow",
  "Diglyceride",
  "Stearic Acid",
  "Magnesium Stearate",
  "Omega-3 Fatty Acids",
  "Vitamin D3 (often derived from lanolin in sheep's wool)",
  "Cysteine",
  "Guanine (E175)",
  "Squalene",
];
List<String> addedSugar = [
  "Agave nectar",
  "Barley malt",
  "Beet sugar",
  "Blackstrap molasses",
  "Brown rice syrup",
  "Brown sugar",
  "Cane crystals",
  "Cane juice",
  "Cane sugar",
  "Caramel",
  "Carob syrup",
  "Castor sugar",
  "Coconut sugar",
  "Confectioner's sugar",
  "Corn sweetener",
  "corn syrup",
  "Corn syrup solids",
  "Crystalline fructose",
  "Date sugar",
  "Demerara sugar",
  "Dextran",
  "Dextrose",
  "Evaporated cane juice",
  "Fructose",
  "Fruit juice concentrate",
  "Galactose",
  "Glucose",
  "Golden syrup",
  "Grape sugar",
  "High-fructose corn syrup",
  "Honey",
  "Icing sugar",
  "Invert sugar",
  "Isomalt",
  "Lactose",
  "Malt extract",
  "Malt syrup",
  "Maltitol",
  "Maltodextrin",
  "Maltose",
  "Maple syrup",
  "Molasses",
  "Monosaccharides",
  "Nectar",
  "Palm sugar",
  "Panocha",
  "Powdered sugar",
  "Raw sugar",
  "Refiner's syrup",
  "Rice syrup",
  "Saccharose",
  "Sorghum syrup",
  "Sucrose",
  "Syrup",
  "Treacle",
  "Turbinado sugar",
  "Yellow sugar",
  "Yacon syrup",
];
List<String> dairy = [
  "Milk",
  "Butter",
  "Cheese",
  "Yogurt",
  "Cream",
  "Sour cream",
  "Cream cheese",
  "Cottage cheese",
  "Mascarpone",
  "Ricotta",
  "Condensed milk",
  "Evaporated milk",
  "Powdered milk",
  "Ice cream",
  "Gelato",
  "Sherbet",
  "Frozen yogurt",
  "Whipped cream",
  "Milk powder",
  "Cheese powder",
  "Whey",
  "Casein",
  "Lactose",
  "Buttermilk",
  "Kefir",
  "Clotted cream",
  "Goat milk",
  "Sheep milk",
  "Buffalo milk",
  "Camel milk",
  "Horse milk",
  "Donkey milk",
  "Moose milk",
  "Reindeer milk",
  "Yak milk",
  "Bison milk",
  "Elk milk",
  "Zebu milk",
  "Ewe milk",
  "Water buffalo milk",
  "A2 milk",
  "Skim milk",
  "Low-fat milk",
  "Full-fat milk",
  "Flavored milk",
  "Chocolate milk",
  "Strawberry milk",
  "Banana milk",
  "Soy yogurt",
  "Milkfat",
  "Skim milk",
  "Milk solids",
  "Milk protein concentrate",
  "Milk protein isolate",
  "Milk permeate",
  "Buttermilk powder",
  "Lactose powder",
  "Whey powder",
  "Whey protein concentrate",
  "Whey protein isolate",
  "Casein powder",
  "Caseinate",
  "Lactalbumin",
  "Lactoferrin",
  "Lactulose",
  "Lactic acid",
  "Galactose",
  "Ghee",
  "Anhydrous milk fat",
  "Buttermilk fat",
  "Cheese whey",
  "Acid whey",
  "Sweet whey",
  "Demarara",
  "Colostrum",
  "Colostrum powder",
  "Colostrum cream",
  "Colostrum butter",
  "Colostrum whey",
  "Colostrum cheese",
  "Colostrum yogurt",
  "Colostrum ice cream",
];
List<String> haram = [];
List<String> heavyMetals = [];
