List<Map<String, List<String>>> keywordLists = [
  // LIST THEM ALL HERE, lowercase and with kebab case
  {"seed-oils": seedOils},
  {"bugs": bugs},
  {"banned-in-eu": bannedInEU},
  {"non-vegetarian": nonVegetarian},
  {"non-vegan": nonVegan},
  {"haram": haram},
  {"heavy-metals": heavyMetals},
  {"added-sugar": addedSugar},
  {"dairy": dairy},
  {"nuts": nuts},
];

List<String> seedOils = [
  "sunflower oil",
  "sunflower lecithin",
  "sesame oil",
  "sesamin",
  "safflower oil",
  "safflower oleosomes",
  "grapeseed oil",
  "grapeseed extract",
  "flaxseed oil",
  "flaxseed meal",
  "chia seed oil",
  "chia seed gel",
  "pumpkin seed oil",
  "pumpkin seed protein",
  "hemp seed oil",
  "hemp seed protein",
  "poppy seed oil",
  "poppy seed paste",
  "mustard seed oil",
  "mustard seed powder",
  "cottonseed oil",
  "cottonseed meal",
  "vegetable oil",
  "canola oil",
  "palm oil",
  "palm kernel oil"
];
List<String> bugs = [
  "Crickets",
  "Cricket flour",
  "Mealworms",
  "Mealworm flour",
  "Black soldier fly larvae",
  "Insect protein isolate",
  "Silkworm pupae",
  "Grasshoppers",
  "Locusts",
  "Ant larvae",
  "Cricket oil",
  "Chitin",
];
List<String> commonAllergens = [
  "Peanuts",
  "almonds",
  "cashews",
  "walnuts",
  "hazelnuts",
  "Milk",
  "Eggs",
  "salmon",
  "tuna",
  "cod",
  "crab",
  "lobster",
  "shrimp",
  "prawns",
  "Wheat",
  "Soy",
  "Sesame seeds",
  "Mustard",
  "Celery",
  "Sulfites",
  "Lupin",
  "snails",
  "squid",
  "octopus",
  "Corn",
  "Gluten",
  "Coconut",
  "Kiwi",
  "Banana",
  "Avocado",
  "Chocolate",
  "Garlic",
  "Onion",
  "Peach",
  "Strawberry",
  "Tomato",
  "Cherry",
  "Pineapple",
  "Melon",
  "Citrus fruits",
  "Apple",
  "Grape",
  "Watermelon",
];

List<String> bannedInEU = [
  "BHA",
  "Butylated Hydroxyanisole",
  "BHT",
  "Butylated Hydroxytoluene",
  "Cyclamate",
  "E952",
  "Aspartame",
  "E951",
  "Tartrazine",
  "E102",
  "Quinoline Yellow",
  "E104",
  "Sunset Yellow FCF",
  "E110",
  "Allura Red AC",
  "E129",
  "Ponceau 4R",
  "E124",
  "Azorubine/Carmoisine",
  "E122",
  "Brominated Vegetable Oil (BVO)",
  "Tartrazine",
  "E102",
  "Quinoline Yellow",
  "E104",
  "Sunset Yellow FCF",
  "E110",
  "Allura Red AC",
  "E129",
  "Ponceau 4R",
  "E124",
  "Azorubine/Carmoisine",
  "E122",
  "Cyclamate",
  "E952",
  "Aspartame",
  "E951",
  "Potassium Nitrate",
  "Sodium Nitrite",
  "Quinines",
  "Monosodium Glutamate",
  "MSG",
];
List<String> nonVegetarian = [
  "Beef",
  "Pork",
  "Chicken",
  "Turkey",
  "Duck",
  "Lamb",
  "Venison",
  "Fish",
  "Shellfish",
  "Shrimp",
  "Crab",
  "Lobster",
  "Mussels",
  "Squid",
  "Octopus",
  "Clams",
  "Anchovies",
  "Bacon",
  "Salmon",
  "Tuna",
  "Sausage",
  "Pepperoni",
  "Ham",
  "Salami",
  "Pate",
  "Liver",
  "Kidney",
  "Tripe",
  "Tongue",
  "Gelatin",
  "Rennet",
  "Worcestershire sauce",
  "Fish sauce",
  "Oyster sauce",
  "Anchovy paste",
  "Isinglass",
  "Lard",
  "Schmaltz",
  "Ghee",
  "clarified butter",
  "Pepsin",
  "Cochineal",
  "Shellac",
  "L-cysteine",
];
List<String> onlyVegan = [
  "Gelatin",
  "Honey",
  "Beeswax",
  "Carmine (E120)",
  "Casein",
  "Lactose",
  "Whey",
  "Isinglass",
  "Shellac (E904)",
  "Lard",
  "Schmaltz",
  "Ghee",
  "clarified butter"
      "Cochineal",
  "Pepsin",
  "Collagen",
  "Elastin",
  "Keratin",
  "Rennet",
  "Tallow",
  "Diglyceride",
  "Stearic Acid",
  "Magnesium Stearate",
  "Omega-3 Fatty Acids",
  "Cysteine",
  "Guanine",
  "Squalene",
];
List<String> nonVegan = [
  ...onlyVegan,
  ...nonVegetarian,
  ...dairy
]; // Poor fucking vegans lol
List<String> addedSugar = [
  "Agave nectar",
  "Barley malt",
  "Beet sugar",
  "Blackstrap molasses",
  "Brown rice syrup",
  "Brown sugar",
  "Cane crystals",
  "Cane juice",
  "Cane sugar",
  "Caramel",
  "Carob syrup",
  "Castor sugar",
  "Coconut sugar",
  "Confectioner's sugar",
  "Corn sweetener",
  "corn syrup",
  "Corn syrup solids",
  "Crystalline fructose",
  "Date sugar",
  "Demerara sugar",
  "Dextran",
  "Dextrose",
  "Evaporated cane juice",
  "Fructose",
  "Fruit juice concentrate",
  "Galactose",
  "Glucose",
  "Golden syrup",
  "Grape sugar",
  "High-fructose corn syrup",
  "Honey",
  "Icing sugar",
  "Invert sugar",
  "Isomalt",
  "Lactose",
  "Malt extract",
  "Malt syrup",
  "Maltitol",
  "Maltodextrin",
  "Maltose",
  "Maple syrup",
  "Molasses",
  "Monosaccharides",
  "Nectar",
  "Palm sugar",
  "Panocha",
  "Powdered sugar",
  "Raw sugar",
  "Refiner's syrup",
  "Rice syrup",
  "Saccharose",
  "Sorghum syrup",
  "Sucrose",
  "Syrup",
  "Treacle",
  "Turbinado sugar",
  "Yellow sugar",
  "Yacon syrup",
];
List<String> dairy = [
  "Milk",
  "Butter",
  "Cheese",
  "Yogurt",
  "Cream",
  "Sour cream",
  "Cream cheese",
  "Cottage cheese",
  "Mascarpone",
  "Ricotta",
  "Condensed milk",
  "Evaporated milk",
  "Powdered milk",
  "Ice cream",
  "Gelato",
  "Sherbet",
  "Frozen yogurt",
  "Whipped cream",
  "Milk powder",
  "Cheese powder",
  "Whey",
  "Casein",
  "Lactose",
  "Buttermilk",
  "Kefir",
  "Clotted cream",
  "Goat milk",
  "Sheep milk",
  "Buffalo milk",
  "Camel milk",
  "Horse milk",
  "Donkey milk",
  "Moose milk",
  "Reindeer milk",
  "Yak milk",
  "Bison milk",
  "Elk milk",
  "Zebu milk",
  "Ewe milk",
  "Water buffalo milk",
  "A2 milk",
  "Skim milk",
  "Low-fat milk",
  "Full-fat milk",
  "Flavored milk",
  "Chocolate milk",
  "Strawberry milk",
  "Banana milk",
  "Soy yogurt",
  "Milkfat",
  "Skim milk",
  "Milk solids",
  "Milk protein concentrate",
  "Milk protein isolate",
  "Milk permeate",
  "Buttermilk powder",
  "Lactose powder",
  "Whey powder",
  "Whey protein concentrate",
  "Whey protein isolate",
  "Casein powder",
  "Caseinate",
  "Lactalbumin",
  "Lactoferrin",
  "Lactulose",
  "Lactic acid",
  "Galactose",
  "Ghee",
  "Anhydrous milk fat",
  "Buttermilk fat",
  "Cheese whey",
  "Acid whey",
  "Sweet whey",
  "Demarara",
  "Colostrum",
  "Colostrum powder",
  "Colostrum cream",
  "Colostrum butter",
  "Colostrum whey",
  "Colostrum cheese",
  "Colostrum yogurt",
  "Colostrum ice cream",
];
List<String> forbiddenPork = [
  "Pork",
  "Gelatin",
  "Lard",
  "Lard oil",
  "Pork flavoring",
  "Bacon",
  "Ham",
  "Sausage",
  "Pork pastrami",
  "prosciutto",
  "pancetta",
  "coppa",
  "capicola",
  "guanciale",
  "fatback",
];
List<String> nuts = [
  "Almonds",
  "Almond butter",
  "Almond extract",
  "Almond meal/flour",
  "Almond milk",
  "Brazil nuts",
  "Cashews",
  "Cashew butter",
  "Cashew milk",
  "Chestnuts",
  "Hazelnuts",
  "Filberts",
  "Hazelnut butter",
  "Hazelnut oil",
  "Macadamia nuts",
  "Macadamia nut oil",
  "Peanuts",
  "Peanut butter",
  "Peanut oil",
  "Pecans",
  "Pine nuts",
  "Pignoli",
  "Pistachios",
  "Walnuts",
  "Nut meal/flour",
  "Nut milk",
  "Nut oil",
  "Nut butter",
  "Nut paste",
  "Nut extract",
  "Marzipan",
  "Almond paste",
  "Praline",
  "Nougat",
  "Gianduja",
  "Hazelnut-chocolate spread",
  "Nut granola/granola bars",
  "Nut cookies/baked goods",
  "Nut ice cream/frozen desserts",
  "Nut toppings",
  "Nut salad dressings",
  "Nut-based sauces",
  "Pesto",
  "Nut stuffing",
  "Nut garnishes",
  "Nut-based spreads/dips",
  "Nut-infused beverages",
  "Nut-filled chocolates/truffles",
  "Nut-based condiments",
  "Nut mustard",
];
List<String> haram = ["Alcohol"];
List<String> heavyMetals = [];
