List<String> seedOils = [
  "Sunflower oil",
  "Sunflower lecithin",
  "Sesame oil",
  "Sesamin",
  "Safflower oil",
  "Safflower oleosomes",
  "Grapeseed oil",
  "Grapeseed extract",
  "Flaxseed oil",
  "Flaxseed meal",
  "Chia seed oil",
  "Chia seed gel",
  "Pumpkin seed oil",
  "Pumpkin seed protein",
  "Hemp seed oil",
  "Hemp seed protein",
  "Poppy seed oil",
  "Poppy seed paste",
  "Mustard seed oil",
  "Mustard seed powder",
  "Cottonseed oil",
  "Cottonseed meal",
];
List<String> bugs = [
"Crickets",
  "Cricket flour",
  "Mealworms",
  "Mealworm flour",
  "Black soldier fly larvae",
  "Insect protein isolate",
  "Silkworm pupae",
  "Grasshoppers",
  "Locusts",
  "Ant larvae",
  "Cricket oil",
  "Chitin",
];
List<String> bannedInEU = [
  "BHA (Butylated Hydroxyanisole)",
  "BHT (Butylated Hydroxytoluene)",
    "Cyclamate (E952)",
  "Aspartame (E951)",
"Tartrazine (E102)",
  "Quinoline Yellow (E104)",
  "Sunset Yellow FCF (E110)",
  "Allura Red AC (E129)",
  "Ponceau 4R (E124)",
  "Azorubine/Carmoisine (E122)",
  "Brominated Vegetable Oil (BVO)",
  "Tartrazine (E102)",
  "Quinoline Yellow (E104)",
  "Sunset Yellow FCF (E110)",
  "Allura Red AC (E129)",
  "Ponceau 4R (E124)",
  "Azorubine/Carmoisine (E122)",
  "Cyclamate (E952)",
  "Aspartame (E951)",
  "Potassium Nitrate",
  "Sodium Nitrite",
  "Quinines",
  "Monosodium Glutamate (MSG)",
];
List<String> nonVeg = [
  "Beef",
  "Pork",
  "Chicken",
  "Turkey",
  "Duck",
  "Lamb",
  "Venison",
  "Fish",
  "Shellfish",
  "Shrimp",
  "Crab",
  "Lobster",
  "Mussels",
  "Squid",
  "Octopus",
  "Clams",
  "Anchovies",
  "Bacon",
  "Salmon",
  "Tuna",
  "Sausage",
  "Pepperoni",
  "Ham",
  "Salami",
  "Pate",
  "Liver",
  "Kidney",
  "Tripe",
  "Tongue",
  "Gelatin",
  "Broth (meat-based)",
"Gelatin",
  "Broth (meat-based)",
  "Rennet",
  "Worcestershire sauce",
  "Fish sauce",
  "Oyster sauce",
  "Anchovy paste",
  "Isinglass",
  "Lard",
  "Schmaltz",
  "Ghee (clarified butter)",
  "Pepsin",
  "Cochineal (E120)",
  "Shellac (E904)",
  "L-cysteine",
];
List<String> nonVegan = [
"Gelatin",
  "Honey",
  "Beeswax",
  "Carmine (E120)",
  "Casein",
  "Lactose",
  "Whey",
  "Isinglass",
  "Shellac (E904)",
  "Lard",
  "Schmaltz",
  "Ghee",
  "clarified butter"
  "Cochineal (E120)",
  "Pepsin",
  "Collagen",
  "Elastin",
  "Keratin",
  "Rennet",
  "Tallow",
  "Diglyceride",
  "Stearic Acid",
  "Magnesium Stearate",
  "Omega-3 Fatty Acids",
  "Vitamin D3 (often derived from lanolin in sheep's wool)",
  "Cysteine",
  "Guanine (E175)",
  "Squalene",
];
